FROM docker.io/library/node:24.19.0@sha256:da4221677e02b54ef6335adfa447578d512ad14f251024fb92ea433c2c102760

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

